hashgraph/hedera-accelerator-defi-dex-ui

README.md
Merging basic changes to the main README file.
=> Merging basic changes to the main README file

architecture/01_Tech_Stack.md, architecture/02_Folder_Structure_Guidelines.md, architecture/03_Redux-like_State_Management.md, architecture/04_CI_CD_Strategy.md, architecture/Architecture_Decision_Record_Template.md
Added architecture decision records for the following topics:
These documents provide important background context regarding why certain technical decisions were made and guidelines around how new code should be organized. These documents act as onboarding references as well as the basis for future technical decision making.
=> docs: [US33739] Added initial set of decision records

.github/workflows/development-deploy.yml, .github/workflows/development-pull-request.yml, .github/workflows/production-deploy.yml, .github/workflows/production-pull-request.yml, package.json, setupTests.ts, src/components/Swap/Swap.tsx, src/components/Swap/__tests__/Swap.test.js, src/hooks/useHashConnect/useHashConnect.ts
- Updated a few tests and files to get the Git Action workflows in a passing state.
- Removed the Github Pages deployment step from the Git Actions workflow. We'll be using Netlify instead.
=> fix: US33715 Fixed RTL test failures

src/components/Swap/Swap.tsx, src/components/base/Inputs/TokenAmountInput.tsx
- RTL tests were failing. I updated the `data-testid` prop for the Token Input components to fix the failing test.
=> fix: pipeline tests

src/HederaOpenDEX/pages/Pool/Pool.tsx
fixing warnings that were breaking ci build
=> chore: fix warnings for ci build

src/HederaOpenDEX/pages/Pool/Pool.tsx, src/context/HashConnectContext.tsx, src/hooks/useHashConnect/useHashConnect.ts, src/hooks/useHederaService/HederaServiceContext.tsx, src/hooks/useHederaService/swapContract.ts
Associate tokens if they dont already exist in wallet when hitting Send 100 L49A and L49B To Wallet button
=> chore: associate lab tokens if needed before transfer

src/components/Swap/Swap.tsx
=> chore: lint fix

src/HederaOpenDEX/HederaOpenDEX.tsx, src/HederaOpenDEX/pages/Pools/Pools.tsx, src/HederaOpenDEX/pages/Pools/index.ts, src/HederaOpenDEX/pages/index.ts, src/components/base/DataTable/DataTable.tsx, src/components/base/DataTable/index.ts
Pools Page and DataTable component
TODO:
-get data from smart contract instaed of using mocks
-probably need reducers and actions to manage this once real data is coming from contract
-mobile view
-need to clean up the pool and liquidity logic
-routing/actions for Create Pool button, Claim Fees button, and Withdraw link. These will be added when those pages are up
=> (feat): DataTable component and Pools page desktop view

src/components/Swap/Swap.tsx, src/components/base/Inputs/SwapSettingsInput.tsx, src/components/base/Inputs/index.ts
UX for Swap Settings
TODO:
-Integrate with actual swap call (will potentially require changes/updates to SwapState, actions, and reducers accordingly in addition to update to smart contract call)
=> Swap settings

src/components/Swap/Swap.tsx, src/components/Swap/actions/actionTypes.ts, src/components/Swap/actions/swapActions.ts, src/components/Swap/reducers/swapReducer.tsx, src/components/Swap/types.ts, src/components/base/Dialogs/AlertDialog.tsx
Swap confirmation dialog
TODO: 
-use smart contract values for transaction and gas fee
-check min received after slippage calculation
-swap loading state dialogs
=> Swap confirmation

src/dex-ui-components/TokenInput/constants.ts, src/dex-ui/pages/Pools/Pools.tsx, src/dex-ui/pages/Withdraw/Withdraw.tsx, src/dex-ui/services/constants.ts
Using Navigation (useNavigation()) to send Location props when navigating from withdraw to pools page to set the local state of whether to show success message and which tab is selected by default
=> Withdraw pools nav

src/dex-ui-components/base/Inputs/TextEditor.tsx, src/dex-ui-components/base/Inputs/styles/TextEditorStyles.ts, src/dex-ui/pages/CreateProposal/ProposalForms/TextProposalForm.tsx, src/dex-ui/pages/CreateProposal/ProposalForms/TokenTransferProposalForm.tsx
=> Input Validations for Rich Text Editor

src/dex-ui-components/base/Card/styles.ts, src/dex-ui-components/base/Inputs/FileUploader.tsx, src/dex-ui-components/base/Inputs/index.ts, src/dex-ui/hooks/governance/index.ts, src/dex-ui/hooks/governance/types.ts, src/dex-ui/hooks/governance/useCreateProposal.tsx, src/dex-ui/hooks/governance/useDeployContract.tsx, src/dex-ui/pages/CreateProposal/ProposalForms/ContractUpgradeProposal/ContractUpgradeProposalForm.tsx, src/dex-ui/pages/CreateProposal/ProposalForms/ContractUpgradeProposal/useContractUpgradeProposalDetails.tsx, src/dex-ui/pages/CreateProposal/ProposalForms/ContractUpgradeProposalForm.tsx, src/dex-ui/pages/CreateProposal/ProposalForms/TokenTransferProposalForm.tsx, src/dex-ui/pages/CreateProposal/ProposalForms/index.ts, src/dex-ui/services/HederaService/GovernorService.ts, src/dex-ui/services/HederaService/types.ts, src/dex-ui/services/HederaService/utils.ts, src/dex-ui/services/constants.ts
=> Contract Upgrade Proposal Form Integration

src/dex-ui/pages/Governance/ProposalCard.tsx, src/dex-ui/utils/styling.ts
=> stripped the HTML and shorten the description on proposal card list page

src/dex-ui-components/base/Inputs/styles/TextEditorStyles.ts, src/dex-ui-components/base/Notification/Notification.tsx, src/dex-ui-components/hooks/usePagination.tsx, src/dex-ui/hooks/governance/index.ts, src/dex-ui/hooks/governance/types.ts, src/dex-ui/hooks/governance/useCancelProposal.tsx, src/dex-ui/pages/ProposalDetails/CancelProposalModalButton.tsx, src/dex-ui/pages/ProposalDetails/ConfirmVoteModalBody.tsx, src/dex-ui/pages/ProposalDetails/ProposalDetails.tsx, src/dex-ui/pages/ProposalDetails/ProposalDetailsControls.tsx, src/dex-ui/pages/ProposalDetails/useProposalDetails.tsx, src/dex-ui/services/HederaService/GovernorService.ts, src/dex-ui/services/HederaService/types.ts
- Added cancelation button, modal, and messaging to the Proposal Details page.
- Added proposal cancelation success notification.
- Cancelation features are only available to the proposal creator.
**Fixes**
- Minor UI fixes for the proposal details description padding and the pagination controls.
=> feat: Proposal Cancelation

src/dex-ui/components/GetTokensButton.tsx, src/dex-ui/components/index.ts, src/dex-ui/pages/AddLiquidity/AddLiquidity.tsx, src/dex-ui/pages/Swap/Swap.tsx, src/dex-ui/services/HederaService/HederaService.ts, src/dex-ui/services/constants.ts, src/dex-ui/store/poolsSlice/poolsSlice.ts, src/dex-ui/store/poolsSlice/types.ts
- Added temporary button and UI elements to transfer L49 test tokens to the connected wallet
=> feat: Added temporary button to transfer L49 test tokens to connected wallet

src/dex-ui-components/SwapTokens/SwapTokens.tsx, src/dex-ui-components/SwapTokens/utils.ts, src/dex-ui/pages/AddLiquidity/AddLiquidity.tsx, src/dex-ui/pages/Withdraw/formatter.ts, src/dex-ui/services/HederaService/HederaService.ts, src/dex-ui/services/HederaService/types.ts, src/dex-ui/services/HederaService/utils.ts, src/dex-ui/services/MirrorNodeService/MirrorNodeService.ts, src/dex-ui/services/MirrorNodeService/types.ts, src/dex-ui/services/constants.ts, src/dex-ui/store/poolsSlice/poolsSlice.ts, src/dex-ui/store/poolsSlice/types.ts, src/dex-ui/store/poolsSlice/utils.ts, src/dex-ui/store/swapSlice/swapSlice.ts, src/dex-ui/utils/poolMetrics.ts
=> HBAR Pair Support in Swap, AddLiquidity and Pool

src/dex-ui/services/constants.ts
- Updated account ids for the Transfer Token contract and Governance token.
=> feat: Updated token transfer and governance token ids

src/dex-ui-components/SwapTokens/SwapTokens.tsx, src/dex-ui-components/TokenInput/constants.ts, src/dex-ui/components/GetTokensButton.tsx, src/dex-ui/hooks/governance/useClaimGODTokens.tsx, src/dex-ui/pages/Governance/Governance.tsx, src/dex-ui/pages/Pools/Pools.tsx, src/dex-ui/pages/ProposalDetails/ProposalDetails.tsx, src/dex-ui/pages/ProposalDetails/ProposalDetailsControls.tsx, src/dex-ui/pages/ProposalDetails/useProposalDetails.tsx, src/dex-ui/services/HederaService/HederaService.ts, src/dex-ui/services/constants.ts, src/dex-ui/utils/formatters.ts
- Updated proposal contract ids. The GOD token address is now updated to the latest governance token address.
- Removed the governance token claim button on the proposal details page.
- Fixed the account id hashscan link on the proposal details page.
=> feat: updated contract ids, removed governance token claim button, fixed account id hashscan link

src/dex-ui/pages/ProposalDetails/ProposalDetailsControls.tsx, src/dex-ui/pages/ProposalDetails/useProposalDetails.tsx, src/dex-ui/store/walletSlice/types.ts, src/dex-ui/store/walletSlice/walletSlice.ts
1. Added Get Dex Coins when user have no GOD Tokens.
2. Add Connect to wallet when wallet is not connected.
=> feat: Voting Flow Enhancements

src/dex-ui-components/SwapTokens/utils.ts, src/dex-ui/pages/AddLiquidity/AddLiquidity.tsx, src/dex-ui/pages/Withdraw/formatter.ts, src/dex-ui/services/HederaService/GovernorService.ts, src/dex-ui/services/HederaService/HederaService.ts, src/dex-ui/services/HederaService/types.ts, src/dex-ui/services/constants.ts, src/dex-ui/store/poolsSlice/poolsSlice.ts, src/dex-ui/store/poolsSlice/utils.ts, src/dex-ui/store/swapSlice/swapSlice.ts, src/dex-ui/utils/poolMetrics.ts
=> Updated the TestNet details along with change the payable method for Swap and Liquidity.

src/dex-ui/services/HederaService/HederaService.ts, src/dex-ui/services/HederaService/types.ts, src/dex-ui/store/poolsSlice/poolsSlice.ts, src/dex-ui/store/swapSlice/swapSlice.ts
Update the Set Payable Method for Add Liquidity and Swap tokens to send 0 quantity when HBAR is selected
=> feat-TA99041: Update the Set Payable Method for new Contract Changes

src/dex-ui-components/base/Button/SettingsButton.tsx, src/dex-ui-components/base/Inputs/Input.tsx, src/dex-ui-components/base/Select/TokenSelector.tsx, src/dex-ui-components/presets/AddLiquidityForm/AddLiquidityForm.tsx, src/dex-ui-components/presets/AddLiquidityForm/constants.ts, src/dex-ui-components/presets/FormSettings/FormSettings.tsx, src/dex-ui-components/presets/SwapTokensForm/SwapTokensForm.tsx, src/dex-ui-components/presets/SwapTokensForm/constants.ts, src/dex-ui-components/presets/constants.ts, src/dex-ui-components/presets/layouts/DefiFormLayout.tsx, src/dex-ui-components/presets/utils.ts, src/dex-ui/hooks/useSwapData.tsx, src/dex-ui/pages/Swap/SwapPage.tsx, src/dex-ui/services/HederaService/HederaService.ts, src/dex-ui/services/contractsUAT.json, src/dex-ui/store/swapSlice/swapSlice.ts, src/dex-ui/store/swapSlice/types.ts, src/dex-ui/utils/numberFormatters.ts
**Features**
- Updated slippage input and added slippage validations
- Added swap form error state when slippage is breached
- Swap transaction now sends the user-entered slippage for smart contract validations
**Fixes**
- Fixed Price Impact calculation
- Fixed pool liquidity rounding error in Zustand store
- Fixed exchange rate to be correctly updated when the Token to Trade and Token to Receive inputs are switched
- Several other minor interaction fixes to the swap form
=> feat: Added slippage input and validations. Added Swap form UI interaction fixes.

src/dex-ui-components/base/Button/SettingsButton.tsx, src/dex-ui-components/presets/AddLiquidityForm/AddLiquidityForm.tsx, src/dex-ui-components/presets/FormSettings/FormSettings.tsx, src/dex-ui-components/presets/FormSettings/useFormSettings.tsx, src/dex-ui-components/presets/SwapTokensForm/SwapTokensForm.tsx, src/dex-ui-components/presets/constants.ts, src/dex-ui-components/presets/layouts/DefiFormLayout.tsx, src/dex-ui/pages/AddLiquidity/AddLiquidityPage.tsx, src/dex-ui/services/HederaService/HederaService.ts, src/dex-ui/services/HederaService/types.ts, src/dex-ui/services/JsonRpcService/Pair.ts, src/dex-ui/store/poolsSlice/poolsSlice.ts, src/dex-ui/store/poolsSlice/types.ts, src/dex-ui/store/poolsSlice/utils.ts, src/dex-ui/store/swapSlice/swapSlice.ts, src/dex-ui/store/swapSlice/types.ts, src/dex-ui/utils/numberFormatters.ts, src/dex-ui/utils/poolMetrics.ts, src/dex-ui/utils/time.ts
**Features**
- Added transaction deadline field and validations for Swap and Add Liquidity Forms
**Fixes**
- Fixed pool metric calculations for HBAR pairs
- Fixed user pool fee display
**Tech Notes**
- A single swap.fetchSpotPrices function is used across swap and pool components (removed the pool.fetchSpotPrices).
=> feat: Add transaction deadline, fix pool metrics

src/dex-ui/pages/Pools/Pools.tsx, src/dex-ui/pages/Withdraw/Withdraw.tsx, src/dex-ui/pages/Withdraw/formatter.ts, src/dex-ui/services/constants.ts
=> Fix not able to withdraw liquidity from pool

src/dex-ui-components/base/Stepper/StepperStyles.ts
=> Fix: Vertical alignment of Proposal Status in details page Stepper UI   

package.json, src/dex-ui-components/index.ts, src/dex-ui/DEX.tsx, src/dex-ui/layouts/DefiFormContainer.tsx, src/dex-ui/layouts/Page.tsx, src/dex-ui/layouts/PageBody.tsx, src/dex-ui/layouts/PageHeader.tsx, src/dex-ui/layouts/TopMenuBar.tsx, src/dex-ui/layouts/index.ts, src/dex-ui/pages/AddLiquidity/AddLiquidityPage.tsx, src/dex-ui/pages/CreatePool/CreatePoolPage.tsx, src/dex-ui/pages/DAOsListPage/DAOCard.tsx, src/dex-ui/pages/DAOsListPage/DAOsListPage.tsx, src/dex-ui/pages/DAOsListPage/index.ts, src/dex-ui/pages/Pools/Pools.tsx, src/dex-ui/pages/Swap/SwapPage.tsx, src/dex-ui/pages/Withdraw/WithdrawPage.tsx, src/dex-ui/pages/index.ts, yarn.lock
🚀 **Features**:
- Added DAO page to navigation options.
- Created DAO list page.
- Added empty state for "no DAOs found" state.
- Created loading state for DAOs list.
⚙️ **Improvements**
- Added `Page` and `DefiFormContainers` wrapper components to establish consistent page padding and presentation.
📷 **Screenshots**
=> feat: Added DAOs list page

src/dex-ui/components/GetTokensButton.tsx, src/dex-ui/services/HederaService/HederaService.ts, src/dex-ui/services/constants.ts
🛠️ Fixes
- Button to send 1000 LAB49A, LAB49B, and LAB49C test tokens fixed.
=> fix: Button to send 1000 LAB49A, LAB49B, and LAB49C tokens

src/dex-ui-components/base/Notification/useNotification.tsx, src/dex-ui-components/base/ProgressBar/ProgressBar.tsx, src/dex-ui-components/base/ProgressBar/index.ts, src/dex-ui-components/base/ProgressBar/useProgressBar.tsx, src/dex-ui-components/base/index.ts, src/dex-ui/hooks/dao/index.ts, src/dex-ui/hooks/dao/types.ts, src/dex-ui/hooks/dao/useCreateMultiSigTransaction.tsx, src/dex-ui/hooks/hederaTokenService/index.ts, src/dex-ui/hooks/hederaTokenService/types.ts, src/dex-ui/hooks/hederaTokenService/useToken.tsx, src/dex-ui/layouts/NotFoundLayout.tsx, src/dex-ui/pages/dao/DAODetailsPage/MultiSigDAODashboard/AssetsList.tsx, src/dex-ui/pages/dao/DAODetailsPage/MultiSigDAODashboard/DashboardHeader.tsx, src/dex-ui/pages/dao/DAODetailsPage/MultiSigDAODashboard/MembersList.tsx, src/dex-ui/pages/dao/DAODetailsPage/MultiSigDAODashboard/MultiSigDAODashboard.tsx, src/dex-ui/pages/dao/DAODetailsPage/MultiSigDAODashboard/TransactionDetails.tsx, src/dex-ui/pages/dao/DAODetailsPage/MultiSigDAODashboard/TransactionsList.tsx, src/dex-ui/pages/dao/DAODetailsPage/MultiSigTransactionModal/MultiSigTransactionDetailsForm.tsx, src/dex-ui/pages/dao/DAODetailsPage/MultiSigTransactionModal/MultiSigTransactionModal.tsx, src/dex-ui/pages/dao/DAODetailsPage/MultiSigTransactionModal/MultiSigTransactionReviewForm.tsx, src/dex-ui/pages/dao/DAODetailsPage/MultiSigTransactionModal/index.ts, src/dex-ui/pages/dao/DAODetailsPage/MultiSigTransactionModal/types.ts
- The user can create a new MultiSig transaction with a custom recipient, token, and amount.
- The transaction will be reflected in the transactions list
=> feat: US34177 MultiSig 'Send Token' modal

aliases.paths.json, craco.config.js, package.json, src/dex-ui-components/base/Breadcrumb/__tests__/Breadcrumb.test.tsx, src/dex-ui/pages/dao/DAOsListPage/DAOsListPage.tsx, src/dex-ui/pages/dao/DAOsListPage/__tests__/DAOsListPage.test.tsx, tsconfig.json, vite.config.ts, yarn.lock
feat: Setup tests for the react using vitest
- Created test config and installed dependencies
- Created dummy tests for page and dumb components.
**Checklist**
=> feat: [DE21905] [UI] Fix private key to string conversion error in Swap RTL tests

src/dex-ui-components/base/Stepper/Steps.tsx, src/dex-ui-components/base/Stepper/index.ts, src/dex-ui/components/Wizard/Wizard.tsx, src/dex-ui/components/Wizard/WizardContext.tsx, src/dex-ui/components/Wizard/WizardStepper.tsx, src/dex-ui/components/Wizard/utils.ts, src/dex-ui/hooks/dao/useDAOTransactions.tsx, src/dex-ui/layouts/ProposalDetailsLayout.tsx, src/dex-ui/pages/dao/SendTokenWizard/SendTokenWizard.tsx, src/dex-ui/pages/dao/TokenTransactionDetails/TokenTransactionDetails.tsx
**Features**
- Created a new standalone `Steps` UI component to replace the `StepperUI` and `StepperV2` components.
- Applied the `Steps` component to the `WizardStepper` component and `Transaction Details` page.
**Tech Notes**
- The `Steps` UI component should be used in place of the `StepperUI` and `StepperV2` components going forward. The `StepperUI` and `StepperV2` components will eventually be deprecated and the dependency on `MUI` can be removed.
=> feat: US34206 Wizard Stepper

src/dex-ui/hooks/dao/useDAOProposals.tsx, src/dex-ui/pages/dao/CreateADAO/CreateADAOPage.tsx, src/dex-ui/pages/dao/DAOProposalVoting.tsx, src/dex-ui/pages/dao/DAOSettings.tsx, src/dex-ui/pages/dao/GovernanceDAODashboard/GovernanceDAODashboardOverview.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/TransactionCard.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/TransactionsList.tsx, src/dex-ui/pages/dao/ProposalCard.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsPage.tsx, src/dex-ui/services/DexService/dao/DAOService.ts, src/dex-ui/services/DexService/dao/types.ts, src/dex-ui/utils/time.ts
Created Governance DAO proposal card
Fixes #
**Checklist**
=> TA99414: Governance DAO Proposal Cards

src/dex-ui-components/themes/textStyles.ts, src/dex-ui/hooks/dao/useDAOProposals.tsx, src/dex-ui/layouts/NotFoundLayout.tsx, src/dex-ui/layouts/TopMenuBar.tsx, src/dex-ui/pages/dao/DAOProposalVoting.tsx, src/dex-ui/pages/dao/DAOSettings.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/DashboardOverview.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/ProposalList.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/Settings.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/index.ts, src/dex-ui/pages/dao/ProposalCard.tsx, src/dex-ui/routes/router.tsx, src/dex-ui/utils/routing.ts
- Populating the Recent Proposals section in MultiSig dashboard (order is based on log index).
- Showing "No proposals found" under the Recent Proposals section.
- Updated Social Link styling
- DAO details are now read-only.
=> feat: UI Enhancements for Demo (Part 1)

src/dex-ui-components/base/ProgressBar/ProgressBar.tsx, src/dex-ui/pages/dao/GovernanceDAODashboard/GovernanceDAODashboardOverview.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/DashboardOverview.tsx, src/dex-ui/pages/dao/RecentProposals.tsx
Added Recent proposals in Governance DAO Dashboard
- Created Recent Proposal component and used it for MultiSig and Governance DAO
Fixes #
**Checklist**
=> feat/US34316: [UI] Governance DAO Recent Proposals 

src/dex-ui-components/base/FormInputList/FormInputList.tsx, src/dex-ui/hooks/dao/index.ts, src/dex-ui/hooks/dao/types.ts, src/dex-ui/hooks/dao/useMintNFT.tsx, src/dex-ui/pages/dao/DAODashboard.tsx, src/dex-ui/pages/dao/DashboardHeader.tsx, src/dex-ui/pages/dao/MintNFTModal.tsx, src/dex-ui/pages/dao/NFTDAODashboard/NFTDAODashboard.tsx, src/dex-ui/pages/dao/types.ts, src/dex-ui/services/HederaService/dao/NFTDAOService.ts, src/dex-ui/services/HederaService/dao/type.ts, src/dex-ui/services/contractsUAT.json
Implemented flow to mint NFT tokens
- Created Modal to mint NFT tokens and Integrated it in NFT DAO Dashboard
- Created Hook to Mint new Tokens for any NFT
Fixes #
**Checklist**
=> Feat/US34242: Mint new NFT 

src/dex-ui-components/base/Pagination/Pagination.tsx, src/dex-ui/layouts/Page.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/ProposalList.tsx, src/dex-ui/services/MirrorNodeService/MirrorNodeService.ts
**NOTE**
For Screenshots / demo the `PageLimit` is set to `2` else its `10` for now.
a
=> feat/US34299: DAO Proposals Pagination

src/dex-ui-components/base/Form/FormDropdown.tsx, src/dex-ui-components/base/Form/index.ts, src/dex-ui-components/base/Inputs/FormInput.tsx, src/dex-ui-components/base/RadioCard/RadioCard.tsx, src/dex-ui-components/base/Select/SelectStyles.ts, src/dex-ui-components/base/index.ts, src/dex-ui/pages/Governance/VotingPower/GOVTokenDetails.tsx, src/dex-ui/pages/Governance/VotingPower/ManageVotingPower.tsx, src/dex-ui/pages/Governance/VotingPower/VotingPower.tsx, src/dex-ui/pages/Governance/VotingPower/types.ts, src/dex-ui/pages/Governance/VotingPower/useManageVotingPower.tsx, src/dex-ui/pages/dao/CreateADAO/forms/CreateTokenDAOGovernanceForm.tsx, src/dex-ui/pages/dao/CreateADAO/forms/TokenDAOVotingForm.tsx, src/dex-ui/pages/dao/DAODashboard.tsx, src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx, src/dex-ui/pages/dao/DAOProposals/Forms/DAOTokenTransferDetailsForm.tsx, src/dex-ui/pages/dao/DAOProposals/types.ts, src/dex-ui/pages/dao/DashboardHeader.tsx, src/dex-ui/pages/dao/GovernanceDAODashboard/GovernanceDAODashboard.tsx, src/dex-ui/pages/dao/GovernanceDAODashboard/GovernanceDAODashboardOverview.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/AssetsList.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/DashboardOverview.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/GovernanceProposalConfirmationDetails.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/GovernanceProposalDetailsPage.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/ProposalVoteModal.tsx, src/dex-ui/routes/router.tsx, src/dex-ui/services/DexService/dao/DAOService.ts, src/dex-ui/services/HederaService/TokenService.ts
- Initial supply input is now equal to the initial supply sent to the network when creating a new token.
- Added quorum validations and warnings.
- Symbol of FT token is shown in place of the "GOV" or "GOD" text.
=> feat: Jul 20 demo enhancements (part 1)

src/dex-ui-components/base/Tabs/TabsStyles.ts, src/dex-ui/pages/dao/CreateADAO/CreateADAOPage.tsx, src/dex-ui/pages/dao/CreateADAO/forms/CreateTokenDAOGovernanceForm.tsx, src/dex-ui/pages/dao/CreateADAO/forms/CreateTokenNFTDAOForm.tsx, src/dex-ui/pages/dao/CreateADAO/forms/DAOTypeForm.tsx, src/dex-ui/pages/dao/CreateADAO/forms/ExistingTokenNFTDAOForm.tsx, src/dex-ui/pages/dao/CreateADAO/forms/NFTDAOGovernanceForm.tsx, src/dex-ui/pages/dao/CreateADAO/forms/NFTDAOReviewForm.tsx, src/dex-ui/pages/dao/CreateADAO/types.ts, src/dex-ui/pages/dao/NFTDAODashboard/NFTDAODashboardOverview.tsx
Updated the flow for NFT Governance while creating a DAO
- Divided the logic to use existing NFT token and mint new token in 2 tabs.
**Related issue(s)
**:
Fixes #
**Checklist**
=> Feat/US34330: NFT governance

src/dex-ui/hooks/dao/types.ts, src/dex-ui/hooks/dao/useDAOProposals.tsx, src/dex-ui/hooks/dao/useGovernanceDAOProposals.tsx, src/dex-ui/pages/dao/CreateADAO/CreateADAOPage.tsx, src/dex-ui/pages/dao/CreateADAO/forms/NFTDAOReviewForm.tsx, src/dex-ui/pages/dao/CreateADAO/forms/NFTDAOVotingForm.tsx, src/dex-ui/pages/dao/CreateADAO/forms/TokenDAOReviewForm.tsx, src/dex-ui/pages/dao/CreateADAO/forms/TokenDAOVotingForm.tsx, src/dex-ui/pages/dao/DAOSettings.tsx, src/dex-ui/pages/dao/GovernanceDAODashboard/GovernanceDAODashboardOverview.tsx, src/dex-ui/pages/dao/NFTDAODashboard/NFTDAODashboardOverview.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/GovernanceProposalConfirmationDetails.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/GovernanceProposalDetailsPage.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/GovernanceProposalDetailsStepper.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsStepper.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/useGovernanceProposalDetails.tsx, src/dex-ui/services/DexService/dao/DAOService.ts, src/dex-ui/services/DexService/governance/GovernanceService.ts, src/dex-ui/services/MirrorNodeService/MirrorNodeService.ts, src/dex-ui/services/contractsUAT.json
=> Fix/US34357: Fix Negative Id error and other bugs

src/dex-ui-components/themes/layerStyles.ts, src/dex-ui/layouts/AppLayout.tsx, src/dex-ui/layouts/CardListLayout.tsx, src/dex-ui/layouts/ErrorLayout.tsx, src/dex-ui/layouts/LoadingSpinnerLayout.tsx, src/dex-ui/layouts/Page.tsx, src/dex-ui/pages/dao/CreateADAO/CreateADAOPage.tsx, src/dex-ui/pages/dao/CreateADAO/forms/MultiSigDAOVotingForm.tsx, src/dex-ui/pages/dao/CreateADAO/forms/constants.ts, src/dex-ui/pages/dao/DAODashboard.tsx, src/dex-ui/pages/dao/DAOSettings.tsx, src/dex-ui/pages/dao/DashboardHeader.tsx, src/dex-ui/pages/dao/GovernanceDAODashboard/GovernanceDAODashboard.tsx, src/dex-ui/pages/dao/GovernanceDAODashboard/GovernanceDAODashboardOverview.tsx, src/dex-ui/pages/dao/GovernanceDAODashboard/types.ts, src/dex-ui/pages/dao/MembersList.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/DashboardOverview.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/MultiSigDAODashboard.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/Settings.tsx
**Features**
- An Admin now counts as a member and impacts the member counts.
- An Admin can now vote on proposals.
- An Admin is automatically added to the members list when creating a new Multisig DAO.
- Updated dashboard stats to reflect the addition of the Admin to the members list.
- Replaced placeholder ("GOV"/"HEY") token symbols with FT token symbols (Fungible Token DAO).
- Added additional styling fixes to the DAO Dashboard pages.
**Screenshots**:
=> feat: Add Admin to MultiSig Member List

src/dex-ui-components/base/Form/FormTokenInput.tsx, src/dex-ui-components/base/Form/index.ts, src/dex-ui-components/base/Form/useHalfMaxButtons.tsx, src/dex-ui-components/base/Inputs/FormInput.tsx, src/dex-ui/pages/Governance/VotingPower/ManageVotingPower.tsx, src/dex-ui/pages/dao/DAOProposals/Forms/DAOTokenTransferDetailsForm.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/AssetsList.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsComponents/ProposalActionDetails.tsx, src/dex-ui/services/constants.ts, src/dex-ui/store/walletSlice/walletSlice.ts
- Amount Input form replaced with Token Input for the Token Transfer Proposal form.
- hbar can now be sent using a Token Transfer Proposal.
=> feat: Create and add Token Input component to Token Transfer form

src/dex-ui-components/WalletConnection/WalletConnection.tsx, src/dex-ui-components/WalletConnection/WalletTokenAssociation.tsx, src/dex-ui-components/WalletConnection/index.ts, src/dex-ui/hooks/token/index.ts, src/dex-ui/hooks/token/types.ts, src/dex-ui/hooks/token/useTokenAssociate.tsx, src/dex-ui/services/HederaService/TokenService.ts
**NOTE**
Showing Already Associated Token wallet error is pending due to some limitations, I will include that in Next PR.
=> feat/US34367: Associate token to user wallet

src/dex-ui/hooks/dao/index.ts, src/dex-ui/hooks/dao/types.ts, src/dex-ui/hooks/dao/useDepositTokens.tsx, src/dex-ui/pages/dao/DAOProposals/Forms/DAOTokenAssociateDetailsForm.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/AssetsList.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/DepositTokensModal.tsx, src/dex-ui/services/HederaService/dao/MultiSigDAOService.ts, src/dex-ui/services/HederaService/dao/type.ts
Implemented deposit flow for assets. 
- Created a popup for depositing assets in MultiSig
- Added a flow to transfer FT ans HBars to  MultiSig Safe
- Added navigation to associate token if token is not present.
Fixes #
**Checklist**
=> Feat/US34352: Deposit button to transfer fund to safe

src/dex-ui/services/contractsUAT.json
Pointing to latest contracts
Swap defect fix
=> Pointing to latest contracts

src/dex-ui-components/WalletConnection/WalletTokenAssociation.tsx, src/dex-ui/hooks/hederaTokenService/useFetchTokenData.tsx, src/dex-ui/hooks/token/useTokenBalance.tsx, src/dex-ui/pages/Governance/VotingPower/useManageVotingPower.tsx
=> feat/US34370-TA99536: Added the Token Already Associated to wallet error in Token Association Flow

src/dex-ui/pages/dao/MultiSigDAODashboard/AssetsList.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/DepositTokensModal.tsx
Added FormTokenInput in the Deposit Asset Modal
Fixes #
**Checklist**
=> Feat/TA99539: Token Input component in Deposit screen.

src/dex-ui/hooks/dao/useCreateDAOTextProposal.tsx, src/dex-ui/hooks/hederaTokenService/index.ts, src/dex-ui/hooks/hederaTokenService/types.ts, src/dex-ui/hooks/hederaTokenService/useTokenNFTs.tsx, src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx, src/dex-ui/pages/dao/DAOProposals/Forms/DAOTextProposalDetailsForm.tsx, src/dex-ui/pages/dao/DAOProposals/Forms/DAOTextProposalReviewForm.tsx, src/dex-ui/pages/dao/DAOProposals/types.ts, src/dex-ui/pages/dao/NFTDAODashboard/NFTDAODashboardOverview.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/GovernanceProposalDetailsPage.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsHeader.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/useGovernanceProposalDetails.tsx, src/dex-ui/routes/router.tsx, src/dex-ui/services/HederaService/TokenService.ts, src/dex-ui/services/HederaService/dao/TokenDAOService.ts, src/dex-ui/services/MirrorNodeService/MirrorNodeService.ts, src/dex-ui/services/MirrorNodeService/types.ts
Implemented flow for NFT Proposals
- Added the Flow to Set NFT allowance to create proposal
- Added the Flow to create Text NFT proposal
- Updated Proposal Details page for NFT proposals.
Fixes #
Voting Flow for NFT Proposals and Other Type of Proposals will be covered in separate PRs. 
**Checklist**
=> Feat/US34315: NFT DAO Proposal Cards & Details

src/dex-ui/pages/dao/DAODashboard.tsx, src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx, src/dex-ui/pages/dao/DAOProposals/Forms/DAOTokenTransferDetailsForm.tsx, src/dex-ui/pages/dao/GovernanceDAODashboard/GovernanceDAODashboard.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/AssetsList.tsx, src/dex-ui/services/DexService/dao/types.ts
Added the Assets flow for the governance DAO
- Added the Assets screen for governance DAO
- Implemented the deposit flow for the governance DAO
- Updated the token transfer flow for the governance DAO
Fixes #
**Checklist**
=> Feat/TA99574: Assets List and Deposit Flow for Governance DAO

src/dao/pages/ProposalDetailsPage/ProposalConfirmationDetails.tsx, src/shared/ui-kit/components/Icons/ToastErrorIcon.tsx, src/shared/ui-kit/components/Icons/ToastInfoIcon.tsx, src/shared/ui-kit/components/Icons/ToastSuccessIcon.tsx, src/shared/ui-kit/components/Icons/ToastWarningIcon.tsx, src/shared/ui-kit/components/Icons/index.ts, src/shared/ui-kit/components/InlineAlert/InlineAlert.tsx, src/shared/ui-kit/components/InlineAlert/index.ts, src/shared/ui-kit/components/Inputs/FormInput.tsx, src/shared/ui-kit/components/index.ts
- Created an `InlineAlert` component in our ui-kit with 4 variations: `Info`, `Warning`, `Error`, `Success`.
- Replaced standalone inline alert components in the `dao` app with the InlineAlert component.
=> feat: Created InlineAlert component

src/dao/hooks/index.ts, src/dao/hooks/types.ts, src/dao/hooks/useFetchLockedNFTToken.tsx, src/dao/hooks/useLockNFTToken.tsx, src/dao/hooks/useManageNFTVotingPower.tsx, src/dao/hooks/useUnlockNFTToken.tsx, src/dao/pages/DAODashboard.tsx, src/dao/pages/NFTVotingPower.tsx, src/dao/pages/ProposalDetailsPage/useGovernanceProposalDetails.tsx, src/dao/services/contracts/NFTDAOService.ts, src/dao/services/types.ts, src/dex/hooks/governance/useLockGODToken.tsx, src/dex/services/HederaService/GovernorService.ts, src/shared/ui-kit/components/VotingPower/GOVTokenDetails.tsx, src/shared/ui-kit/components/VotingPower/ManageVotingPower.tsx, src/shared/ui-kit/components/VotingPower/VotingPower.tsx, src/shared/ui-kit/components/VotingPower/index.ts, src/shared/ui-kit/components/VotingPower/types.ts, src/shared/ui-kit/components/index.ts
Implemented manage voting power flow for NFT DAOs.
- Created a component to  show locked, unlocked NFT Tokens.
- Created a component to lock, unlock NFT tokens.
- Implemented the methods to lock, unlock NFT tokens.
- Updated the flow to lock GOD tokens in Governance DAO.
Fixes #
**Checklist**
=> Feat: US34411: NFT Lock Tokens for Voting

src/dao/services/DAOService.ts, src/dao/services/contracts/TokenDAOService.ts, src/dao/services/contracts/types.ts, src/dao/services/types.ts
Added Support for Hbar transfer in Gov DAO
Fixes #
**Checklist**
=> Feat/US34429: Hbar token transfer for Gov DAO

src/dao/hooks/useCreateDAOTokenTransferProposal.tsx, src/dao/hooks/useCreateGOVTokenAssociateProposal.tsx, src/dao/pages/DAOProposals/CreateDAOProposal.tsx, src/dao/pages/DAOProposals/Forms/DAOProposalTypeForm.tsx, src/dao/pages/DAOProposals/Forms/DAOTokenAssociateDetailsForm.tsx, src/dao/pages/DAOProposals/Forms/DAOTokenAssociateReviewForm.tsx, src/dao/pages/DAOProposals/Forms/DAOTokenTransferDetailsForm.tsx, src/dao/pages/DAOProposals/Forms/DAOTokenTransferReviewForm.tsx, src/dao/pages/DAOProposals/types.ts, src/dao/pages/NFTDAODashboard/NFTDAODashboard.tsx, src/dao/routes/router.tsx, src/dao/services/contracts/TokenDAOService.ts
Added Assets in NFT DAOs.
- Added Assets screen for the NFT DAO.
- Implemented flow to associate, deposit and transfer FT tokens in NFT DAO.
Fixes #
**Checklist**
=> Feat/US34433: NFT Assets Screen

src/dao/hooks/useDepositTokens.tsx, src/dao/pages/MultiSigDAODashboard/AssetsList.tsx, src/dao/pages/MultiSigDAODashboard/DepositTokensModal.tsx, src/dao/pages/MultiSigDAODashboard/types.ts, src/dao/services/contracts/MultiSigDAOService.ts, src/dex/hooks/hederaTokenService/useAccountTokenBalances.tsx, src/dex/services/DexService/token/TokenService.ts, src/shared/services/MirrorNodeService/types.ts, src/shared/ui-kit/components/FormTokenInput/FormTokenInputSelectTokenModal.tsx
Implemented Deposit Flow for NFTs
Fixes #
**Checklist**
=> Feat/US34437: Add NFT serial id to various flows and assets tab

src/dao/hooks/index.ts, src/dao/hooks/types.ts, src/dao/hooks/useFetchDAOMembers.tsx, src/dao/pages/GovernanceDAODashboard/GovernanceDAODashboard.tsx, src/dao/pages/NFTDAODashboard/NFTDAODashboard.tsx, src/dao/services/types.ts, src/dex/hooks/governance/useLockGODToken.tsx, src/dex/hooks/governance/useUnlockGODToken.tsx, src/dex/services/DexService/governance/GovernanceService.ts, src/dex/services/DexService/governance/type.ts
=> feat/US34475: Members list for locked tokens in GOV and NFT DAO

src/dao/pages/GovernanceDAODashboard/GovernanceDAODashboard.tsx, src/dao/pages/GovernanceDAODashboard/types.ts, src/dao/pages/MultiSigDAODashboard/AssetsList.tsx, src/dao/pages/MultiSigDAODashboard/MultiSigDAODashboard.tsx, src/dao/pages/MultiSigDAODashboard/types.ts, src/dao/pages/NFTDAODashboard/NFTDAODashboard.tsx, src/dao/pages/NFTDAODashboard/types.ts
Asset List was not loading due to a missing parameter "blockedBalance" in `outlet` of multisig causing the asset list for multisig loading issue.
=> fix: Asset list loading issue for multisig

src/dao/hooks/useDAOProposals.tsx, src/dao/hooks/useFetchDAOMembers.tsx, src/dao/hooks/useFetchLockedNFTToken.tsx, src/dao/hooks/useGovernanceDAOProposals.tsx, src/dao/pages/DAOProposals/CreateDAOProposal.tsx, src/dao/pages/GovernanceDAODashboard/GovernanceDAODashboard.tsx, src/dao/pages/MultiSigDAODashboard/AssetsList.tsx, src/dao/pages/NFTDAODashboard/NFTDAODashboard.tsx, src/dao/pages/ProposalDetailsPage/useGovernanceProposalDetails.tsx, src/dao/pages/utils.ts, src/dao/services/DAOService.ts, src/dao/services/contracts/TokenDAOService.ts, src/dex/hooks/governance/useFetchLockedGovToken.tsx, src/dex/services/DexService/governance/GovernanceService.ts, src/dex/services/JsonRpcService/Factory.ts, src/dex/services/JsonRpcService/Pair.ts, src/dex/services/JsonRpcService/utils.ts, src/shared/utils/utils.ts
Replaced deprecated functions from Hashgraph SDK
Fixes #
**Checklist**
=> Fix/US34461: Replace Deprecated Functions of Hashgraph 

src/dao/hooks/index.ts, src/dao/hooks/types.ts, src/dao/hooks/useCreateMultiSigProposal.tsx, src/dao/hooks/useDAOProposals.tsx, src/dao/hooks/useFetchContract.tsx, src/dao/hooks/useGovernanceDAOProposals.tsx, src/dao/pages/DAODashboard.tsx, src/dao/pages/DAOProposals/CreateDAOProposal.tsx, src/dao/pages/DAOsListPage/DAOCard.tsx, src/dao/pages/DashboardHeader.tsx, src/dao/pages/MultiSigDAODashboard/AssetsList.tsx, src/dao/pages/MultiSigDAODashboard/DashboardOverview.tsx, src/dao/pages/MultiSigDAODashboard/MultiSigDAODashboard.tsx, src/dao/pages/MultiSigDAODashboard/ProposalList.tsx, src/dao/pages/ProposalCard.tsx, src/dao/pages/ProposalDetailsPage/ProposalConfirmationDetails.tsx, src/dao/pages/ProposalDetailsPage/ProposalDetailsPage.tsx, src/dao/pages/ProposalDetailsPage/useProposalDetails.tsx, src/dao/pages/UpdateDAODetails/UpdateDAODetails.tsx, src/dao/services/DAOService.ts, src/dao/services/contracts/MultiSigDAOService.ts, src/dao/services/types.ts, src/dex/services/constants.ts, src/dex/services/contractsUAT.json, src/shared/services/MirrorNodeService/types.ts
Updated flow for MultiSig DAO
- Created useContract hook
- removed API calls from fetchMutiSigDAOs and used useContract hook to fetch contract Id
Fixes #
**Checklist**
=> Feat/TA99668: Implement useContractId hook in MultiSig DAO

src/dao/DAO.tsx, src/dex/DEX.tsx, src/dex/hooks/useLocalStorage.ts, src/shared/ui-kit/components/Modal/modalStyles.ts, src/shared/ui-kit/components/TermsConditionModal/TermsConditionModal.tsx, src/shared/ui-kit/components/TermsConditionModal/index.ts, src/shared/ui-kit/components/WalletConnection/WalletConnection.tsx, src/shared/ui-kit/components/constants.ts, src/shared/ui-kit/components/index.ts
Created the Terms and Condition Modal Component
- Saved acceptedState in the local storage
- Show modal if Terms and Conditions are not accepted
Fixes #
Terms and Condition Text is not provided by client till now. so used lorem ipsum placeholder text for the time being.
**Checklist**
=> Feat/US34501: Terms and Conditions Modal

README.md, src/dex/context/constants.ts, src/dex/pages/Governance/VotingPower/VotingPower.tsx, src/dex/routes/router.tsx
**Disable Deprecated Governance from DEX**
=> feat/US34515: Disable Deprecated Governance from DEX

src/dao/hooks/useCreateDAOUpgradeProposal.tsx, src/dao/pages/DAOProposals/CreateDAOProposal.tsx, src/dao/pages/DAOProposals/Forms/DAOContractUpgradeDetailsForm.tsx, src/dao/pages/DAOProposals/Forms/DAOContractUpgradeReviewForm.tsx, src/dao/pages/DAOProposals/types.ts, src/dao/pages/NFTDAODashboard/NFTDAODashboard.tsx, src/dao/pages/NFTDAODashboard/NFTDAODashboardOverview.tsx, src/dao/pages/NFTDAODashboard/types.ts, src/dao/services/contracts/TokenDAOService.ts, src/shared/services/MirrorNodeService/types.ts
Updated the Contract Upgrade Proposal
- Added the proxy admin input in the form.
- Added the Unit of Gov Token in NFT DAO Overview.
Fixes #
**Checklist**
=> Feat/US34519: Add field for proxy admin in upgrade contract proposal

api/ipfs.ts, api/pinToIPFS.ts, src/dao/hooks/IPFS/useIPFSContent.tsx, src/dao/hooks/IPFS/usePinToIPFS.tsx, src/dao/hooks/useGovernanceDAOProposals.tsx, src/dao/pages/DAOProposals/CreateDAOProposal.tsx, src/dao/pages/ProposalDetailsPage/GovernanceProposalDetailsPage.tsx, src/dao/pages/ProposalDetailsPage/ProposalDetails.tsx, src/dao/services/IPFSService.ts, src/shared/services/MirrorNodeService/types.ts, src/shared/ui-kit/components/Dialogs/LoadingDialog.tsx
- Added UI error handling for errors thrown when pining IPFS data or fetching IPFS data from Pinata.
=> feat: Added UI error messaging for IPFS pinning / fetching errors

src/dao/hooks/useFetchDAOConfig.tsx, src/dao/pages/CreateADAO/CreateADAOPage.tsx, src/dao/pages/CreateADAO/forms/DAODetailsForm.tsx, src/dao/pages/CreateADAO/forms/DAOTypeForm.tsx, src/dao/pages/CreateADAO/types.ts, src/dex/utils/poolMetrics.ts, src/shared/ui-kit/components/Inputs/FormInput.tsx
**Note**
This PR is dependent on https://github.com/hashgraph/hedera-accelerator-defi-dex-ui/pull/269 since there is flow change to fetch the DAO fee details to show in UI and will be merged after combining the changes of above mentioned PR.
=> Feat/US34526: Show DAO fee in DAO Details Page

src/dao/hooks/types.ts, src/dao/pages/DAOsListPage/DAOsListPage.tsx, src/dao/pages/utils.ts, src/dao/services/DAOService.ts, src/dao/services/types.ts, src/dex/layouts/CardGridLayout.tsx, src/dex/layouts/NotFoundLayout.tsx, src/dex/services/constants.ts
Updated the DAO home page
- Added Tabs for All DAOs and My DAOs.
- Added Filter based on DAO title, description and type.
- Added Skeleton cards for loading state in DAOs Home page.
Fixes #
**Checklist**
=> Feat/US34409: Update DAO Homepage

yarn.lock
- Reverted recent cryptography-related package versions
=> fix: Encryption error message when connecting wallet

src/dao/hooks/useCreateMultiSigGenericProposal.tsx
now fetching SafeAddress from MirrorNode.
=> Fix: Asset Transfer via Generic Proposal

package.json, src/dao/pages/CreateADAO/CreateADAOPage.tsx, src/dao/pages/CreateADAO/forms/DAODisclaimerForm.tsx, src/dao/pages/CreateADAO/forms/NFTDAOVotingForm.tsx, src/dao/pages/CreateADAO/forms/TokenDAOVotingForm.tsx, src/dao/pages/CreateADAO/forms/constants.ts, src/dao/pages/CreateADAO/forms/index.ts, src/dao/pages/CreateADAO/types.ts, src/dao/pages/DAODashboard.tsx, src/dao/routes/router.tsx, src/dao/routes/routes.ts, src/index.tsx
add's a spot for a click-through disclaimer when creating a DAO
=> feat: add disclaimer to DAO page

src/dex/layouts/PageFooter.tsx
=> fix: fix copyright

src/dao/pages/ProposalCard.tsx, src/dao/pages/ProposalDetailsPage/ProposalDetailsComponents/ProposalActionDetails.tsx, src/dex/layouts/TopMenuBar.tsx, src/shared/ui-kit/components/FormTokenInput/FormTokenInputSelectTokenButton.tsx, src/shared/ui-kit/components/FormTokenInput/FormTokenInputSelectTokenModal.tsx, src/shared/ui-kit/components/Icons/HederaIcon.tsx, src/shared/ui-kit/components/Icons/index.ts
fix: revert hederaicon for use as hbar icon
Fixes #
**Checklist**
=> feat: use full logo in navbar

index.html, src/shared/ui-kit/components/Icons/HashDaoIcon.tsx, src/shared/ui-kit/components/Icons/HashDaoLogo.tsx
=> fix: fix site name

index.html
=> fix: amend meta

src/dao/pages/DAOsListPage/DAOsListPage.tsx, src/dao/pages/MultiSigDAODashboard/DepositTokensModal.tsx
=> fix: wording

src/dao/pages/DAOsListPage/DAOsListPage.tsx
=> fix: wording on mainsite

package.json
=> fix: add overrides

.github/workflows/production-deploy.yml, .github/workflows/production-pull-request.yml
Updating workflow permissions as per step-security needs.
Fixes #377 
**Checklist**
=> chore: Updating workflow permissions as per step-security.

src/dex/hooks/governance/useFetchLockedGovToken.tsx, src/dex/hooks/governance/useUnlockGODToken.tsx, src/dex/pages/Governance/VotingPower/useManageVotingPower.tsx
Fixes for:
- `governance-token/<token_id>/overview` page, lock amounts
=> bugfix: fix lock token amounts

src/dao/hooks/useFetchDAOConfig.tsx, src/dao/services/contracts/TokenDAOService.ts, src/dex/services/constants.ts, src/dex/utils/poolMetrics.ts
=> Fix for hbar config mismatch
