hashgraph/hedera-accelerator-defi-dex-ui

.github/workflows/production-deploy.yml, .github/workflows/production-pull-request.yml, package.json, src/HederaOpenDEX/pages/Trade/Trade.tsx, src/components/Swap/Swap.tsx, src/components/base/Buttons/styles/ButtonStyles.ts, src/components/base/Dialogs/AlertDialog.tsx, src/context/HashConnectContext.tsx, src/hooks/useHashConnect/actions/actionsTypes.ts, src/hooks/useHashConnect/actions/hashConnectActions.ts, src/hooks/useHashConnect/useHashConnect.ts, src/hooks/useHashConnect/useHashConnectEvents.ts, src/hooks/useHederaService/HederaServiceContext.tsx, src/hooks/useHederaService/swapContract.ts, src/middleware/loggerMiddleware.ts, src/middleware/thunkMiddleware.ts
Note that the `@typescript-eslint/no-explicit-any` and `react-hooks/exhaustive-deps` rules should be reenabled in the near future.
=> refactor: fix / update code base on tslint warnings 

package.json, src/hooks/useHashConnect/useHashConnectEvents.ts, yarn.lock
Upgrading `hashconnect` from `0.1.0` to `0.2.2` breaks the wallet pairing functionality. We are reverting this upgrade for now.
=> fix: downgrade hashconnect from v0.2.2-> v0.1.10

package.json, src/components/Swap/Swap.tsx, src/components/Swap/actions/actionTypes.ts, src/components/Swap/actions/swapActions.ts, src/components/Swap/reducers/swapReducer.tsx, src/components/Swap/utils.ts, src/components/TokenInput/TokenInput.tsx, yarn.lock
**UI Changes**:
**Technical Updates**
More details: https://alexsidorenko.com/blog/react-update-nested-state/
=> feat: US33774 Interaction Enhancements to Token Input components

src/HederaOpenDEX/pages/Trade/Trade.tsx, src/components/Swap/Swap.tsx, src/components/Swap/__fixtures__/swap.ts, src/components/Swap/actions/swapActions.ts, src/components/Swap/reducers/swapReducer.tsx, src/components/Swap/types.ts, src/context/HashConnectContext.tsx, src/hooks/useHashConnect/actions/actionsTypes.ts, src/hooks/useHashConnect/actions/hashConnectActions.ts, src/hooks/useHashConnect/reducers/hashConnectReducer.ts, src/hooks/useHashConnect/useHashConnect.ts, src/hooks/useHederaService/swapContract.ts
Price impact display and updates to computation of calculating the token to receive value. Updated token to receive computation to abide by the CPMM algorithm where (X+newX)*(Y-newY) = K. Plug in values and solve for newY previously was using spot price directly 
A few issues/things to note:
-need to revisit the Swap calculation and make sure this is the correct way 
-when switching token selection, it makes a smart contract call to get the spot price. this has some latency and we should perhaps add some UX to show that price impact as well as the new price needs some time to be calculated (as we need to retrieve liquidity of both tokens to determine price impact as well as the token to receive value)
-There is a weird issue when clicking the switch token to trade and token to receive …
=> feat: spot price display and update to token to receive calculation

src/HederaOpenDEX/HederaOpenDEX.tsx, src/HederaOpenDEX/pages/Pools/Pools.tsx, src/HederaOpenDEX/pages/Pools/utils.ts, src/hooks/constants.ts, src/hooks/useMirrorNode/services.ts, src/hooks/useMirrorNode/types.ts, src/hooks/useMirrorNode/useMirrorNode.ts, src/hooks/useMirrorNode/utils/poolMetrics.ts
- User pool metrics are fetched, formatted, and displayed in the Pool UI table.
- All pool metrics now correctly aggregate token **credit and debit** transactions in volume calculations.
- The Mirror Node API limits returned data to 100 records. I've incorporated logic that will make subsequent calls to the Mirror Node API to get the full batch of records. A function will fetch and aggregate batches of 100 records until the Mirror Node API no longer returns a **link.next** URL, i.e. all records for the query have been accounted for.
- Pool and User Pool balances are saved in MirrorNodeState.
=> feat: Updates to All & User Pool Metrics

package.json, src/dex-ui-components/SwapTokens/utils.ts, src/dex-ui-components/base/Charts/HorizontalStackedBarChart.tsx, src/dex-ui-components/base/Charts/Metrics.tsx, src/dex-ui-components/base/Charts/index.ts, src/dex-ui-components/base/Inputs/SwapSettingsInput.tsx, src/dex-ui-components/base/Inputs/styles/NumberInputStyles.ts, src/dex-ui-components/base/index.ts, src/dex-ui/DEX.tsx, src/dex-ui/pages/Governance/Governance.tsx, src/dex-ui/pages/Governance/ProposalCard.tsx, src/dex-ui/pages/Governance/formatter.ts, src/dex-ui/pages/Governance/types.ts, src/dex-ui/pages/ProposalDetails/ProposalDetails.tsx, src/dex-ui/pages/ProposalDetails/index.ts, src/dex-ui/pages/index.ts, src/dex-ui/services/HederaService/HederaService.ts, src/dex-ui/services/HederaService/types.ts, src/dex-ui/services/MirrorNodeService/MirrorNodeService.ts, src/dex-ui/services/MirrorNodeService/types.ts, src/dex-ui/services/abi/GovernorCountingSimpleInternal.json, src/dex-ui/services/constants.ts, src/dex-ui/store/governanceSlice/governanceSlice.ts, src/dex-ui/store/governanceSlice/type.ts, src/dex-ui/store/governanceSlice/utils.ts, src/dex-ui/utils/time.ts, yarn.lock
- Fetching all proposals from events emitted from the smart contract through a mirror node API endpoint.
- Created horizontal stacked bar chart component for vote count display.
- Converted proposal block numbers to human readable time durations.
**Fixes**
- Updated `HederaService` read-only contract calls to use `ContractCallQuery` instead of `ContractExecuteTransaction`. This reduces the hbar costs of executing these queries.
=> feat: Fetch Proposal Data and Display in Governance List

src/dex-ui/pages/CreateProposal/ProposalForms/TextProposalForm.tsx, src/dex-ui/pages/CreateProposal/ProposalForms/TokenTransferProposalForm.tsx, src/dex-ui/pages/Governance/ProposalCard.tsx, src/dex-ui/pages/Governance/formatter.ts, src/dex-ui/pages/Governance/types.ts, src/dex-ui/pages/ProposalDetails/ProposalDetails.tsx, src/dex-ui/services/HederaService/GovernorService.ts, src/dex-ui/services/HederaService/HederaService.ts, src/dex-ui/services/HederaService/types.ts, src/dex-ui/services/HederaService/utils.ts, src/dex-ui/services/MirrorNodeService/MirrorNodeService.ts, src/dex-ui/services/MirrorNodeService/types.ts, src/dex-ui/store/governanceSlice/governanceSlice.ts, src/dex-ui/store/governanceSlice/type.ts, src/dex-ui/store/walletSlice/types.ts, src/dex-ui/store/walletSlice/walletSlice.ts
- Updated `Text Proposal ` form UI. Can create text proposal with new `GovernorTextProposal` contract.
- Added Cancel button to `Create Proposal` forms.
- Proposal type tag added to `All Proposals` list and `Proposal Details` page.
- Added logic to fetch proposals across all proposal contract types.
- Updated `HederaService` functions to match new proposal proxy contract functions.
- Added `Execute` button and execute functionality `Proposal Details` page. Note: The full `execute` UI flow and functionality will be merged in subsequent PR. The execute contract call currently fails with a "Transfer token failed." error - similar to the issue we're seeing with `swapToken` calls.
=> feat: Added execute button, text proposal form, and logic to manage proposal types

src/dex-ui/services/MirrorNodeService/MirrorNodeService.ts, src/dex-ui/services/MirrorNodeService/constants.ts, src/dex-ui/services/MirrorNodeService/utils.ts, src/dex-ui/services/abi/types.ts
- Fetching all proposal types in governance proposal list with new event log decoding logic.
**Tech Notes**
- Added `getFulfilledResultsData` utility function to filter results from `Promise.allSettled`.
=> feat: US33917 Re-enabled proposal fetching for all proposal types

src/dex-ui/services/HederaService/GovernorService.ts, src/dex-ui/services/HederaService/HederaService.ts, src/dex-ui/services/constants.ts
In this PR:
From Backend we changed the approach from HTS to ERC20 to transfer the token which does not require Private key for transferring tokens, based on which we do not require the sign the transaction second time using Dex Private key in UI.
=> Feat: Removed Private key dependencies from Transactions (swap, withdraw)

src/dex-ui/pages/Governance/formatter.ts, src/dex-ui/services/constants.ts
Since the Voting count logic is changed from percentage to GOD tokens quantity the UI needed a fix on numbers as the UI was still using the percentage based system. 
=> feat-US34029: Quick Fix the Voting numbers on UI side

src/dex-ui-components/presets/AddLiquidityForm/AddLiquidityForm.tsx, src/dex-ui-components/presets/FormSettings/useFormSettings.tsx, src/dex-ui-components/presets/SwapTokensForm/SwapTokensForm.tsx
- Moved duplicate settings logic to `useFormSettings` hook. This is intended to be used across Defi forms.
- Removed duplicate token input handlers in the AddLiquidity form.
=> refactor: Moved duplicate form settings logic to single hook

src/dex-ui/services/DexService/DexService.ts
**Fixes**
- Partial fix for the "undefined votes" error on the governance page. The unsuccessful fetching of proposal voting data causes this error.
=> fix: Partial fix for undefined vote counts (when vote fetching fails)

src/dex-ui/pages/dao/CreateADAO/CreateADAOPage.tsx, src/dex-ui/pages/dao/CreateADAO/forms/DAODetailsForm.tsx
🛠️ Fixes
- The Logo URL field in the Create DAO Wizard is no longer required to create a DAO
📝 Tech Notes
- The DAO Smart Contracts currently require a Logo URL with a length greater than 1. This bugfix requires changes on smart contracts to work end-to-end. Smart Contract PR: https://github.com/hashgraph/hedera-accelerator-defi-dex/pull/445
=> fix: Made DAO logo field optional

package.json, yarn.lock
**Tech Notes**
- Removed `react-router` as a dependency. `react-router-dom` contains all of the features from `react-router`.
=> feat: Removed Duplicate react-router Dependency

src/dex-ui-components/base/Icons/CheckCircleUnfilledIcon.tsx, src/dex-ui-components/base/Icons/index.ts, src/dex-ui/hooks/dao/useDAOTransactions.tsx, src/dex-ui/pages/ProposalDetails/ProposalDetailsControls.tsx, src/dex-ui/pages/dao/MultiSigTransactionModal/MultiSigTransactionReviewForm.tsx, src/dex-ui/pages/dao/TokenTransactionDetails/TokenTransactionDetails.tsx
**Context**
The Safe contract allows a single owner to approve transactions multiple times. The confirmation count in the contract state is only incremented once but an `ApproveHash` event is emitted every time the owner sends an approval transaction. This causes the UI to show duplicate confirmations.
**Features**
- The disabled "Confirmed by you" button is displayed if the currently connected wallet has already confirmed the Token Transfer transaction.
- Confirmation counts no longer incorporate duplicate confirmations.
**Tech Notes**
- Logic to gather `approvals` account ID list and `approvalCount` has been updated to filter out duplicate ApproveHash events.
=> feat: [US34213] Prevent Duplicate Owner Confirmations

src/dex-ui/hooks/governance/useExecuteProposal.tsx, src/dex-ui/pages/CreateProposal/ProposalForms/TokenTransferProposalForm.tsx, src/dex-ui/pages/ProposalDetails/ProposalDetailsControls.tsx, src/dex-ui/services/DexService/governance/GovernanceService.ts, src/dex-ui/services/HederaService/GovernorService.ts, src/dex-ui/services/JsonRpcService/Governor.ts, src/dex-ui/services/MirrorNodeService/types.ts, src/dex-ui/services/abi/GovernorCountingSimpleInternal.json, src/dex-ui/services/contractsUAT.json, src/dex-ui/store/governanceSlice/type.ts
1. This PR sets up token Allowance for Token Transfer before executing.
2. The `tokenTransferDetails` are only fetched when fetching the proposal details in "Proposal Details" page on the list page the details are not required as of now.
1. I was able to test only once with proposal due to the issue with testnet (I will run some more test on the same)
=> feat/US34227 - Set Token Allowance for Token Transfer Proposal before Execution as a part of v36 security changes

src/dex-ui/pages/dao/DAODashboard.tsx, src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/MultiSigDAODashboard.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsPage.tsx, src/dex-ui/pages/dao/SendTokenWizard/SendTokenWizard.tsx, src/dex-ui/routes/router.tsx, src/dex-ui/routes/routes.ts
- Changed `dashboard` tab to `overview`
- Routes were changed from `dashboard` to `overview` as well
=> feat: Changed dashboard tab to overview

src/dex-ui/pages/dao/CreateADAO/forms/MultiSigDAOVotingForm.tsx, src/dex-ui/pages/dao/CreateADAO/forms/constants.ts, src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx, src/dex-ui/pages/dao/DAOProposals/Forms/DAOProposalTypeForm.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/DashboardOverview.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/ProposalList.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetails.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsComponents/ProposalActionDetails.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsComponents/ProposalTransactionDetails.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsPage.tsx
- Added `Not Found `components for proposal lists.
- Removed the `created` field from proposal details.
- Removed `Text` type from MultiSig DAO proposal type selector.
- Removed `admin` from max threshold count when creating a new MultiSig DAO.
- New Proposal title changes based on the selected proposal type.
- Fixed rounding for Token Transfer amounts in the proposal details page.
**Screenshot**
=> feat: Additional UI Enhancements for MultiSig DAO v1

src/dex-ui/pages/dao/DAOProposals/Forms/DAOTokenTransferDetailsForm.tsx, src/dex-ui/pages/dao/MultiSigDAODashboard/AssetsList.tsx
Implemented Send token for MultiSig Assets
- navigate from assets to token transfer form
- auto populate fields based on asset.
- added dropdown for tokens to select.
Fixes #
**Checklist**
=> Feat/US-34355: Send button on Asset cards the opens token transfer proposal with auto populated  fields

src/dex-ui/pages/dao/ProposalDetailsPage/GovernanceProposalDetailsStepper.tsx, src/dex-ui/pages/dao/utils.ts
https://github.com/hashgraph/hedera-accelerator-defi-dex-ui/pull/200
Wrap this logic in a function.
Change the variable declaration from let => const
Call the new function and return the steps and activeStep values instead of mutating the variables.
Wrapped Proposal detail stepper logic in function.
Fixes #
**Checklist**
=> Fix/TA99548: Fix Comments for merged PR

src/dex-ui/hooks/dao/types.ts, src/dex-ui/pages/dao/ProposalCard.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/GovernanceProposalConfirmationDetails.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/GovernanceProposalDetailsPage.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsComponents/ProposalCancelModal.tsx, src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsComponents/index.ts, src/dex-ui/pages/dao/constants.ts, src/dex-ui/pages/dao/utils.ts
Fixed the UI for Voting Section in Governance DAO Proposal Details.
- Disabled Voting Button If Voting Power is Zero
- Show Cancel Button If Proposal State is Failed/Defeated/Queued.
- UI correction for Vote, Cancel and execute,
Fixes #
**Checklist**
=> Fix/TA99537: Governance Voting UI Issues

src/dex-ui/pages/CreateProposal/ProposalForms/ContractUpgradeProposalForm.tsx, src/dex-ui/pages/CreateProposal/ProposalForms/TextProposalForm.tsx, src/dex-ui/pages/CreateProposal/ProposalForms/TokenTransferProposalForm.tsx, src/dex-ui/pages/Governance/VotingPower/ManageVotingPower.tsx, src/dex-ui/pages/ProposalDetails/ProposalDetailsControls.tsx, src/dex-ui/pages/ProposalDetails/useProposalDetails.tsx, src/dex-ui/services/constants.ts, src/dex-ui/store/swapSlice/swapSlice.ts
** Description **
This PR fixes multiple issue's in Prod under Swap, Governance and Manage Voting Power.
**Swap**:
When Swapping any `token` for `HBAR` HBAR was getting associated to wallet which is fixed now.
**Governance**
1.`Cancel` proposal was not available for the active proposals it was only available when proposal is ready for `Execute`, the problem being if proposal was defeated there was not way for the user to get back locked token from `ManageVotingPower` since `GOD Holder` does not allow `unlocking` the tokens. The `cancel button` will be visible until the proposal is not executed or cancelled already.
2. Corrected the UI for Manage Voting Power in case of already active proposals when user goes to `Unlock` tab.
=> Fix-US34370-TA99546: HBAR Association to wallet in Swap, Fix Cancel Button Not visible for Governance

src/dex-ui-components/base/Form/index.ts, src/dex-ui-components/base/Form/useFormTokenInputPattern.tsx, src/dex-ui-components/base/Form/useHalfMaxButtons.tsx, src/dex-ui/pages/dao/DAOProposals/Forms/DAOTokenTransferDetailsForm.tsx, src/dex-ui/pages/dao/DAOProposals/types.ts
- Created a `useFormTokenInputPattern` hook that can be used to apply a regex guard to input components (intended to be used with Token Input components).
- Changing the assets dropdown no longer sets the value in the amount input.
**Pattern Details**
```
/**
* Regex pattern used to restrict the values a user can enter in a token input component.
*
* @remarks
* - The regex `/^(0|[1-9]\d*)?(\.\d*)?$/` matches a floating-point number in the string.
* - The first part of the regex, `^(0|[1-9]\d*)?`, matches an optional leading zero or a sequence of one or more
* digits.
* - The second part of the regex, `(\.\d*)?`, matches an optional decimal point followed by zero or more digits.
* @example
* For example, the following strings would all match the regex:
* ```
* "0"
* "1.23" …
=> feat: Pattern input constraints for Token Input component

src/dao/hooks/useDAOProposals.tsx, src/dao/services/DAOService.ts, src/dex/hooks/governance/useAllProposals.tsx, src/dex/hooks/governance/useProposal.tsx, src/dex/pages/Governance/Governance.tsx, src/dex/pages/ProposalDetails/useProposalDetails.tsx, src/dex/services/DexService/governance/GovernanceService.ts, src/dex/services/constants.ts, src/shared/services/MirrorNodeService/MirrorNodeService.ts
With latest testing it came out the user is not able to remove the member using proposal in MultiSig DAO.
With recent addition of admin as member the member list was not in correct order since we need to send `prevOwner` as parameter in order to create a proposal.
With new `callContract` API available we can not fetch exact list of owners in actual order rather reading and making a list of member operations. this solves the problem.
=> Fix/DE21946-feat/US34453: fetch member list, updated threshold using new call contract api

.github/CODEOWNERS, .github/workflows/production-deploy.yml, .github/workflows/production-pull-request.yml
Updates the self-hosted runner label to be defi-dex-linux-medium runner group. Adds CODEOWNERS to the repo.
Fixes #355
=> ci: Update self-hosted runner group and CODEOWNERS

package.json
**Details**:
Needed to add scope to the package in package.json
**Related Issue(s)**
Fixes #384
=> chore: Add scope to package name in package.json
